FROM python:3.9
ENV root_dir=/mnt/core_llm_home/code
ENV module=atg_platform_streamlit
ENV TZ="America/Los_Angeles"
CMD set -x;cd $root_dir;pwd;\
    now=$(date +%Y_%m_%d_%H_%M_%S) && mkdir $now && cd $now;pwd;\
    git clone -b prod --single-branch https://parthamukherjeesnow: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@github.com/ServiceNow/${module}.git; \
    [ -d $root_dir/$module/backup ] && cp -r $root_dir/$module/backup ./$module; \
    [ -d $root_dir/$module/config ] && cp -r $root_dir/$module/config ./$module; \
    [ -d $root_dir/$module/data ] && cp -r $root_dir/$module/data ./$module; \
    [ -d $root_dir/$module/endpoints ] && cp -r $root_dir/$module/endpoints ./$module;\
    cd $root_dir; echo "Root Dir:$root_dir";echo "Module:$module";pwd;ls; \
    [ -d $module ] && mv $module retired_$module_$now; \
    mv $now/$module . &&\
    rm -rf $root_dir/$now &&\
    rm -rf $root_dir/$module/results && ln -s /mnt/core_llm_home/streamlit $root_dir/$module/results
